(cl:in-package uav_msgs-msg)
(cl:export '(CX-VAL
          CX
          CY-VAL
          CY
          W-VAL
          W
          H-VAL
          H
          SCORE-VAL
          SCORE
          CATEGORY-VAL
          CATEGORY
          CATEGORY_ID-VAL
          CATEGORY_ID
          TRACKED_ID-VAL
          TRACKED_ID
          PX-VAL
          PX
          PY-VAL
          PY
          PZ-VAL
          PZ
          LOS_AX-VAL
          LOS_AX
          LOS_AY-VAL
          LOS_AY
          YAW_A-VAL
          YAW_A
          MODE-VAL
          MODE
          SIM_SCORE-VAL
          SIM_SCORE
))