
(cl:in-package :asdf)

(defsystem "uav_msgs-msg"
  :depends-on (:roslisp-msg-protocol :roslisp-utils :std_msgs-msg
)
  :components ((:file "_package")
    (:file "HoverCommand" :depends-on ("_package_HoverCommand"))
    (:file "_package_HoverCommand" :depends-on ("_package"))
    (:file "LandCommand" :depends-on ("_package_LandCommand"))
    (:file "_package_LandCommand" :depends-on ("_package"))
    (:file "PositionControlGlobalCommand" :depends-on ("_package_PositionControlGlobalCommand"))
    (:file "_package_PositionControlGlobalCommand" :depends-on ("_package"))
    (:file "PositionControlNEDCommand" :depends-on ("_package_PositionControlNEDCommand"))
    (:file "_package_PositionControlNEDCommand" :depends-on ("_package"))
    (:file "ReturnToLaunchCommand" :depends-on ("_package_ReturnToLaunchCommand"))
    (:file "_package_ReturnToLaunchCommand" :depends-on ("_package"))
    (:file "SetModeCommand" :depends-on ("_package_SetModeCommand"))
    (:file "_package_SetModeCommand" :depends-on ("_package"))
    (:file "TakeoffCommand" :depends-on ("_package_TakeoffCommand"))
    (:file "_package_TakeoffCommand" :depends-on ("_package"))
    (:file "UAVControlCommand" :depends-on ("_package_UAVControlCommand"))
    (:file "_package_UAVControlCommand" :depends-on ("_package"))
    (:file "VelocityControlNEDCommand" :depends-on ("_package_VelocityControlNEDCommand"))
    (:file "_package_VelocityControlNEDCommand" :depends-on ("_package"))
  ))