# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from uav_msgs/Target.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Target(genpy.Message):
  _md5sum = "3623dd3b471832f212700e5baf3ce9ed"
  _type = "uav_msgs/Target"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
## 目标中心的水平位置 [0,1]
float32 cx
## 目标中心的垂直位置 [0,1]
float32 cy

## 目标宽度/图像宽度 [0,1]
float32 w
## 目标高度/图像高度 [0,1]
float32 h

## 目标置信度 [0,1]
float32 score

## 目标类别名称
string category
## 目标类别编号 从0开始计算
int32 category_id

## 目标跟踪ID号
int32 tracked_id

## 目标3D位置 单位：m
float32 px
float32 py
float32 pz

## 目标中心点的视线角度 [相机系下：右方x角度为正，下方y角度为正] 单位：度
float32 los_ax
float32 los_ay

## 偏航角误差 [图像系下：垂直向上为0°，右半圈顺时针0~180°，左半圈逆时针0~-180°]
float32 yaw_a

## detection(false/0) or tracked(true/1)
bool mode

## CosineSimilarity
float32 sim_score




"""
  __slots__ = ['cx','cy','w','h','score','category','category_id','tracked_id','px','py','pz','los_ax','los_ay','yaw_a','mode','sim_score']
  _slot_types = ['float32','float32','float32','float32','float32','string','int32','int32','float32','float32','float32','float32','float32','float32','bool','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       cx,cy,w,h,score,category,category_id,tracked_id,px,py,pz,los_ax,los_ay,yaw_a,mode,sim_score

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Target, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.cx is None:
        self.cx = 0.
      if self.cy is None:
        self.cy = 0.
      if self.w is None:
        self.w = 0.
      if self.h is None:
        self.h = 0.
      if self.score is None:
        self.score = 0.
      if self.category is None:
        self.category = ''
      if self.category_id is None:
        self.category_id = 0
      if self.tracked_id is None:
        self.tracked_id = 0
      if self.px is None:
        self.px = 0.
      if self.py is None:
        self.py = 0.
      if self.pz is None:
        self.pz = 0.
      if self.los_ax is None:
        self.los_ax = 0.
      if self.los_ay is None:
        self.los_ay = 0.
      if self.yaw_a is None:
        self.yaw_a = 0.
      if self.mode is None:
        self.mode = False
      if self.sim_score is None:
        self.sim_score = 0.
    else:
      self.cx = 0.
      self.cy = 0.
      self.w = 0.
      self.h = 0.
      self.score = 0.
      self.category = ''
      self.category_id = 0
      self.tracked_id = 0
      self.px = 0.
      self.py = 0.
      self.pz = 0.
      self.los_ax = 0.
      self.los_ay = 0.
      self.yaw_a = 0.
      self.mode = False
      self.sim_score = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5f().pack(_x.cx, _x.cy, _x.w, _x.h, _x.score))
      _x = self.category
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2i6fBf().pack(_x.category_id, _x.tracked_id, _x.px, _x.py, _x.pz, _x.los_ax, _x.los_ay, _x.yaw_a, _x.mode, _x.sim_score))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.cx, _x.cy, _x.w, _x.h, _x.score,) = _get_struct_5f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.category = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.category = str[start:end]
      _x = self
      start = end
      end += 37
      (_x.category_id, _x.tracked_id, _x.px, _x.py, _x.pz, _x.los_ax, _x.los_ay, _x.yaw_a, _x.mode, _x.sim_score,) = _get_struct_2i6fBf().unpack(str[start:end])
      self.mode = bool(self.mode)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5f().pack(_x.cx, _x.cy, _x.w, _x.h, _x.score))
      _x = self.category
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2i6fBf().pack(_x.category_id, _x.tracked_id, _x.px, _x.py, _x.pz, _x.los_ax, _x.los_ay, _x.yaw_a, _x.mode, _x.sim_score))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.cx, _x.cy, _x.w, _x.h, _x.score,) = _get_struct_5f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.category = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.category = str[start:end]
      _x = self
      start = end
      end += 37
      (_x.category_id, _x.tracked_id, _x.px, _x.py, _x.pz, _x.los_ax, _x.los_ay, _x.yaw_a, _x.mode, _x.sim_score,) = _get_struct_2i6fBf().unpack(str[start:end])
      self.mode = bool(self.mode)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i6fBf = None
def _get_struct_2i6fBf():
    global _struct_2i6fBf
    if _struct_2i6fBf is None:
        _struct_2i6fBf = struct.Struct("<2i6fBf")
    return _struct_2i6fBf
_struct_5f = None
def _get_struct_5f():
    global _struct_5f
    if _struct_5f is None:
        _struct_5f = struct.Struct("<5f")
    return _struct_5f
