# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from uav_msgs/UAVControlCommand.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import uav_msgs.msg

class UAVControlCommand(genpy.Message):
  _md5sum = "53572dae1fc3b49d99d763590ada7f7d"
  _type = "uav_msgs/UAVControlCommand"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
string command_type
time timestamp
int32 target_system

TakeoffCommand takeoff
LandCommand land
PositionControlNEDCommand pos_ned
PositionControlGlobalCommand pos_global
VelocityControlNEDCommand vel_ned
ReturnToLaunchCommand rtl
HoverCommand hover
SetModeCommand set_mode
WaypointsCommand waypoints_cmd

================================================================================
MSG: uav_msgs/TakeoffCommand
float64 altitude
float64 yaw

================================================================================
MSG: uav_msgs/LandCommand
float64 yaw

================================================================================
MSG: uav_msgs/PositionControlNEDCommand
float64 x
float64 y
float64 z
float64 yaw

================================================================================
MSG: uav_msgs/PositionControlGlobalCommand
float64 latitude
float64 longitude
float64 altitude
float64 yaw

================================================================================
MSG: uav_msgs/VelocityControlNEDCommand
float64 vx
float64 vy
float64 vz
float64 yaw_rate

================================================================================
MSG: uav_msgs/ReturnToLaunchCommand
float64 altitude

================================================================================
MSG: uav_msgs/HoverCommand
string mode
================================================================================
MSG: uav_msgs/SetModeCommand
string mode

================================================================================
MSG: uav_msgs/WaypointsCommand
bool start_immediately     # 是否立即执行航点
Waypoint[] waypoints       # 航点列表
================================================================================
MSG: uav_msgs/Waypoint
int32 waypoint_id          # 航点ID
string frame               # 坐标系类型
string command             # 航点指令类型
float64 latitude           # 纬度 (度)
float64 longitude          # 经度 (度)
float64 altitude           # 高度 (米)
bool is_current            # 是否为当前航点
bool autocontinue          # 是否自动继续到下一个航点
float64 hold_time          # 悬停时间 (秒)"""
  __slots__ = ['command_type','timestamp','target_system','takeoff','land','pos_ned','pos_global','vel_ned','rtl','hover','set_mode','waypoints_cmd']
  _slot_types = ['string','time','int32','uav_msgs/TakeoffCommand','uav_msgs/LandCommand','uav_msgs/PositionControlNEDCommand','uav_msgs/PositionControlGlobalCommand','uav_msgs/VelocityControlNEDCommand','uav_msgs/ReturnToLaunchCommand','uav_msgs/HoverCommand','uav_msgs/SetModeCommand','uav_msgs/WaypointsCommand']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       command_type,timestamp,target_system,takeoff,land,pos_ned,pos_global,vel_ned,rtl,hover,set_mode,waypoints_cmd

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(UAVControlCommand, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.command_type is None:
        self.command_type = ''
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      if self.target_system is None:
        self.target_system = 0
      if self.takeoff is None:
        self.takeoff = uav_msgs.msg.TakeoffCommand()
      if self.land is None:
        self.land = uav_msgs.msg.LandCommand()
      if self.pos_ned is None:
        self.pos_ned = uav_msgs.msg.PositionControlNEDCommand()
      if self.pos_global is None:
        self.pos_global = uav_msgs.msg.PositionControlGlobalCommand()
      if self.vel_ned is None:
        self.vel_ned = uav_msgs.msg.VelocityControlNEDCommand()
      if self.rtl is None:
        self.rtl = uav_msgs.msg.ReturnToLaunchCommand()
      if self.hover is None:
        self.hover = uav_msgs.msg.HoverCommand()
      if self.set_mode is None:
        self.set_mode = uav_msgs.msg.SetModeCommand()
      if self.waypoints_cmd is None:
        self.waypoints_cmd = uav_msgs.msg.WaypointsCommand()
    else:
      self.command_type = ''
      self.timestamp = genpy.Time()
      self.target_system = 0
      self.takeoff = uav_msgs.msg.TakeoffCommand()
      self.land = uav_msgs.msg.LandCommand()
      self.pos_ned = uav_msgs.msg.PositionControlNEDCommand()
      self.pos_global = uav_msgs.msg.PositionControlGlobalCommand()
      self.vel_ned = uav_msgs.msg.VelocityControlNEDCommand()
      self.rtl = uav_msgs.msg.ReturnToLaunchCommand()
      self.hover = uav_msgs.msg.HoverCommand()
      self.set_mode = uav_msgs.msg.SetModeCommand()
      self.waypoints_cmd = uav_msgs.msg.WaypointsCommand()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.command_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2Ii16d().pack(_x.timestamp.secs, _x.timestamp.nsecs, _x.target_system, _x.takeoff.altitude, _x.takeoff.yaw, _x.land.yaw, _x.pos_ned.x, _x.pos_ned.y, _x.pos_ned.z, _x.pos_ned.yaw, _x.pos_global.latitude, _x.pos_global.longitude, _x.pos_global.altitude, _x.pos_global.yaw, _x.vel_ned.vx, _x.vel_ned.vy, _x.vel_ned.vz, _x.vel_ned.yaw_rate, _x.rtl.altitude))
      _x = self.hover.mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.set_mode.mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.waypoints_cmd.start_immediately
      buff.write(_get_struct_B().pack(_x))
      length = len(self.waypoints_cmd.waypoints)
      buff.write(_struct_I.pack(length))
      for val1 in self.waypoints_cmd.waypoints:
        _x = val1.waypoint_id
        buff.write(_get_struct_i().pack(_x))
        _x = val1.frame
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.command
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_3d2Bd().pack(_x.latitude, _x.longitude, _x.altitude, _x.is_current, _x.autocontinue, _x.hold_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      if self.takeoff is None:
        self.takeoff = uav_msgs.msg.TakeoffCommand()
      if self.land is None:
        self.land = uav_msgs.msg.LandCommand()
      if self.pos_ned is None:
        self.pos_ned = uav_msgs.msg.PositionControlNEDCommand()
      if self.pos_global is None:
        self.pos_global = uav_msgs.msg.PositionControlGlobalCommand()
      if self.vel_ned is None:
        self.vel_ned = uav_msgs.msg.VelocityControlNEDCommand()
      if self.rtl is None:
        self.rtl = uav_msgs.msg.ReturnToLaunchCommand()
      if self.hover is None:
        self.hover = uav_msgs.msg.HoverCommand()
      if self.set_mode is None:
        self.set_mode = uav_msgs.msg.SetModeCommand()
      if self.waypoints_cmd is None:
        self.waypoints_cmd = uav_msgs.msg.WaypointsCommand()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.command_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.command_type = str[start:end]
      _x = self
      start = end
      end += 140
      (_x.timestamp.secs, _x.timestamp.nsecs, _x.target_system, _x.takeoff.altitude, _x.takeoff.yaw, _x.land.yaw, _x.pos_ned.x, _x.pos_ned.y, _x.pos_ned.z, _x.pos_ned.yaw, _x.pos_global.latitude, _x.pos_global.longitude, _x.pos_global.altitude, _x.pos_global.yaw, _x.vel_ned.vx, _x.vel_ned.vy, _x.vel_ned.vz, _x.vel_ned.yaw_rate, _x.rtl.altitude,) = _get_struct_2Ii16d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.hover.mode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.hover.mode = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.set_mode.mode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.set_mode.mode = str[start:end]
      start = end
      end += 1
      (self.waypoints_cmd.start_immediately,) = _get_struct_B().unpack(str[start:end])
      self.waypoints_cmd.start_immediately = bool(self.waypoints_cmd.start_immediately)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.waypoints_cmd.waypoints = []
      for i in range(0, length):
        val1 = uav_msgs.msg.Waypoint()
        start = end
        end += 4
        (val1.waypoint_id,) = _get_struct_i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.frame = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.frame = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.command = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.command = str[start:end]
        _x = val1
        start = end
        end += 34
        (_x.latitude, _x.longitude, _x.altitude, _x.is_current, _x.autocontinue, _x.hold_time,) = _get_struct_3d2Bd().unpack(str[start:end])
        val1.is_current = bool(val1.is_current)
        val1.autocontinue = bool(val1.autocontinue)
        self.waypoints_cmd.waypoints.append(val1)
      self.timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.command_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2Ii16d().pack(_x.timestamp.secs, _x.timestamp.nsecs, _x.target_system, _x.takeoff.altitude, _x.takeoff.yaw, _x.land.yaw, _x.pos_ned.x, _x.pos_ned.y, _x.pos_ned.z, _x.pos_ned.yaw, _x.pos_global.latitude, _x.pos_global.longitude, _x.pos_global.altitude, _x.pos_global.yaw, _x.vel_ned.vx, _x.vel_ned.vy, _x.vel_ned.vz, _x.vel_ned.yaw_rate, _x.rtl.altitude))
      _x = self.hover.mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.set_mode.mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.waypoints_cmd.start_immediately
      buff.write(_get_struct_B().pack(_x))
      length = len(self.waypoints_cmd.waypoints)
      buff.write(_struct_I.pack(length))
      for val1 in self.waypoints_cmd.waypoints:
        _x = val1.waypoint_id
        buff.write(_get_struct_i().pack(_x))
        _x = val1.frame
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.command
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_3d2Bd().pack(_x.latitude, _x.longitude, _x.altitude, _x.is_current, _x.autocontinue, _x.hold_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      if self.takeoff is None:
        self.takeoff = uav_msgs.msg.TakeoffCommand()
      if self.land is None:
        self.land = uav_msgs.msg.LandCommand()
      if self.pos_ned is None:
        self.pos_ned = uav_msgs.msg.PositionControlNEDCommand()
      if self.pos_global is None:
        self.pos_global = uav_msgs.msg.PositionControlGlobalCommand()
      if self.vel_ned is None:
        self.vel_ned = uav_msgs.msg.VelocityControlNEDCommand()
      if self.rtl is None:
        self.rtl = uav_msgs.msg.ReturnToLaunchCommand()
      if self.hover is None:
        self.hover = uav_msgs.msg.HoverCommand()
      if self.set_mode is None:
        self.set_mode = uav_msgs.msg.SetModeCommand()
      if self.waypoints_cmd is None:
        self.waypoints_cmd = uav_msgs.msg.WaypointsCommand()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.command_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.command_type = str[start:end]
      _x = self
      start = end
      end += 140
      (_x.timestamp.secs, _x.timestamp.nsecs, _x.target_system, _x.takeoff.altitude, _x.takeoff.yaw, _x.land.yaw, _x.pos_ned.x, _x.pos_ned.y, _x.pos_ned.z, _x.pos_ned.yaw, _x.pos_global.latitude, _x.pos_global.longitude, _x.pos_global.altitude, _x.pos_global.yaw, _x.vel_ned.vx, _x.vel_ned.vy, _x.vel_ned.vz, _x.vel_ned.yaw_rate, _x.rtl.altitude,) = _get_struct_2Ii16d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.hover.mode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.hover.mode = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.set_mode.mode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.set_mode.mode = str[start:end]
      start = end
      end += 1
      (self.waypoints_cmd.start_immediately,) = _get_struct_B().unpack(str[start:end])
      self.waypoints_cmd.start_immediately = bool(self.waypoints_cmd.start_immediately)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.waypoints_cmd.waypoints = []
      for i in range(0, length):
        val1 = uav_msgs.msg.Waypoint()
        start = end
        end += 4
        (val1.waypoint_id,) = _get_struct_i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.frame = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.frame = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.command = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.command = str[start:end]
        _x = val1
        start = end
        end += 34
        (_x.latitude, _x.longitude, _x.altitude, _x.is_current, _x.autocontinue, _x.hold_time,) = _get_struct_3d2Bd().unpack(str[start:end])
        val1.is_current = bool(val1.is_current)
        val1.autocontinue = bool(val1.autocontinue)
        self.waypoints_cmd.waypoints.append(val1)
      self.timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2Ii16d = None
def _get_struct_2Ii16d():
    global _struct_2Ii16d
    if _struct_2Ii16d is None:
        _struct_2Ii16d = struct.Struct("<2Ii16d")
    return _struct_2Ii16d
_struct_3d2Bd = None
def _get_struct_3d2Bd():
    global _struct_3d2Bd
    if _struct_3d2Bd is None:
        _struct_3d2Bd = struct.Struct("<3d2Bd")
    return _struct_3d2Bd
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
