
plugin_blacklist:
# common
- safety_area
# extras
- image_pub
- vibration
#- distance_sensor
# - rangefinder
- wheel_odometry


plugin_whitelist: []

# 如果只想启用 lidar/flow，也可以用 whitelist，例如：
# plugin_whitelist: [distance_sensor, px4flow, rangefinder]
