// Generated by gencpp from file uav_msgs/PositionControlGlobalCommand.msg
// DO NOT EDIT!


#ifndef UAV_MSGS_MESSAGE_POSITIONCONTROLGLOBALCOMMAND_H
#define UAV_MSGS_MESSAGE_POSITIONCONTROLGLOBALCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_msgs
{
template <class ContainerAllocator>
struct PositionControlGlobalCommand_
{
  typedef PositionControlGlobalCommand_<ContainerAllocator> Type;

  PositionControlGlobalCommand_()
    : latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , yaw(0.0)  {
    }
  PositionControlGlobalCommand_(const ContainerAllocator& _alloc)
    : latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _altitude_type;
  _altitude_type altitude;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::uav_msgs::PositionControlGlobalCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_msgs::PositionControlGlobalCommand_<ContainerAllocator> const> ConstPtr;

}; // struct PositionControlGlobalCommand_

typedef ::uav_msgs::PositionControlGlobalCommand_<std::allocator<void> > PositionControlGlobalCommand;

typedef boost::shared_ptr< ::uav_msgs::PositionControlGlobalCommand > PositionControlGlobalCommandPtr;
typedef boost::shared_ptr< ::uav_msgs::PositionControlGlobalCommand const> PositionControlGlobalCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_msgs::PositionControlGlobalCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_msgs::PositionControlGlobalCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_msgs::PositionControlGlobalCommand_<ContainerAllocator1> & lhs, const ::uav_msgs::PositionControlGlobalCommand_<ContainerAllocator2> & rhs)
{
  return lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.altitude == rhs.altitude &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_msgs::PositionControlGlobalCommand_<ContainerAllocator1> & lhs, const ::uav_msgs::PositionControlGlobalCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::PositionControlGlobalCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::PositionControlGlobalCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::PositionControlGlobalCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::PositionControlGlobalCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::PositionControlGlobalCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::PositionControlGlobalCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_msgs::PositionControlGlobalCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5313e55a66285d01bb2325b7f49eeadb";
  }

  static const char* value(const ::uav_msgs::PositionControlGlobalCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5313e55a66285d01ULL;
  static const uint64_t static_value2 = 0xbb2325b7f49eeadbULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_msgs::PositionControlGlobalCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_msgs/PositionControlGlobalCommand";
  }

  static const char* value(const ::uav_msgs::PositionControlGlobalCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_msgs::PositionControlGlobalCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 latitude\n"
"float64 longitude\n"
"float64 altitude\n"
"float64 yaw\n"
;
  }

  static const char* value(const ::uav_msgs::PositionControlGlobalCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_msgs::PositionControlGlobalCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PositionControlGlobalCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_msgs::PositionControlGlobalCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_msgs::PositionControlGlobalCommand_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_MSGS_MESSAGE_POSITIONCONTROLGLOBALCOMMAND_H
