// Generated by gencpp from file uav_msgs/ReturnToLaunchCommand.msg
// DO NOT EDIT!


#ifndef UAV_MSGS_MESSAGE_RETURNTOLAUNCHCOMMAND_H
#define UAV_MSGS_MESSAGE_RETURNTOLAUNCHCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_msgs
{
template <class ContainerAllocator>
struct ReturnToLaunchCommand_
{
  typedef ReturnToLaunchCommand_<ContainerAllocator> Type;

  ReturnToLaunchCommand_()
    : altitude(0.0)  {
    }
  ReturnToLaunchCommand_(const ContainerAllocator& _alloc)
    : altitude(0.0)  {
  (void)_alloc;
    }



   typedef double _altitude_type;
  _altitude_type altitude;





  typedef boost::shared_ptr< ::uav_msgs::ReturnToLaunchCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_msgs::ReturnToLaunchCommand_<ContainerAllocator> const> ConstPtr;

}; // struct ReturnToLaunchCommand_

typedef ::uav_msgs::ReturnToLaunchCommand_<std::allocator<void> > ReturnToLaunchCommand;

typedef boost::shared_ptr< ::uav_msgs::ReturnToLaunchCommand > ReturnToLaunchCommandPtr;
typedef boost::shared_ptr< ::uav_msgs::ReturnToLaunchCommand const> ReturnToLaunchCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_msgs::ReturnToLaunchCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_msgs::ReturnToLaunchCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_msgs::ReturnToLaunchCommand_<ContainerAllocator1> & lhs, const ::uav_msgs::ReturnToLaunchCommand_<ContainerAllocator2> & rhs)
{
  return lhs.altitude == rhs.altitude;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_msgs::ReturnToLaunchCommand_<ContainerAllocator1> & lhs, const ::uav_msgs::ReturnToLaunchCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::ReturnToLaunchCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::ReturnToLaunchCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::ReturnToLaunchCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::ReturnToLaunchCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::ReturnToLaunchCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::ReturnToLaunchCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_msgs::ReturnToLaunchCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "42af7eb0aaf91dc07d6880f800cabbb3";
  }

  static const char* value(const ::uav_msgs::ReturnToLaunchCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x42af7eb0aaf91dc0ULL;
  static const uint64_t static_value2 = 0x7d6880f800cabbb3ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_msgs::ReturnToLaunchCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_msgs/ReturnToLaunchCommand";
  }

  static const char* value(const ::uav_msgs::ReturnToLaunchCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_msgs::ReturnToLaunchCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 altitude\n"
;
  }

  static const char* value(const ::uav_msgs::ReturnToLaunchCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_msgs::ReturnToLaunchCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.altitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReturnToLaunchCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_msgs::ReturnToLaunchCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_msgs::ReturnToLaunchCommand_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_MSGS_MESSAGE_RETURNTOLAUNCHCOMMAND_H
