// Generated by gencpp from file uav_msgs/TakeoffCommand.msg
// DO NOT EDIT!


#ifndef UAV_MSGS_MESSAGE_TAKEOFFCOMMAND_H
#define UAV_MSGS_MESSAGE_TAKEOFFCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_msgs
{
template <class ContainerAllocator>
struct TakeoffCommand_
{
  typedef TakeoffCommand_<ContainerAllocator> Type;

  TakeoffCommand_()
    : altitude(0.0)
    , yaw(0.0)  {
    }
  TakeoffCommand_(const ContainerAllocator& _alloc)
    : altitude(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef double _altitude_type;
  _altitude_type altitude;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::uav_msgs::TakeoffCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_msgs::TakeoffCommand_<ContainerAllocator> const> ConstPtr;

}; // struct TakeoffCommand_

typedef ::uav_msgs::TakeoffCommand_<std::allocator<void> > TakeoffCommand;

typedef boost::shared_ptr< ::uav_msgs::TakeoffCommand > TakeoffCommandPtr;
typedef boost::shared_ptr< ::uav_msgs::TakeoffCommand const> TakeoffCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_msgs::TakeoffCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_msgs::TakeoffCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_msgs::TakeoffCommand_<ContainerAllocator1> & lhs, const ::uav_msgs::TakeoffCommand_<ContainerAllocator2> & rhs)
{
  return lhs.altitude == rhs.altitude &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_msgs::TakeoffCommand_<ContainerAllocator1> & lhs, const ::uav_msgs::TakeoffCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::TakeoffCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::TakeoffCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::TakeoffCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::TakeoffCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::TakeoffCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::TakeoffCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_msgs::TakeoffCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "83cd6ff07b4a0c35e09bcaacfdff250a";
  }

  static const char* value(const ::uav_msgs::TakeoffCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x83cd6ff07b4a0c35ULL;
  static const uint64_t static_value2 = 0xe09bcaacfdff250aULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_msgs::TakeoffCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_msgs/TakeoffCommand";
  }

  static const char* value(const ::uav_msgs::TakeoffCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_msgs::TakeoffCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 altitude\n"
"float64 yaw\n"
;
  }

  static const char* value(const ::uav_msgs::TakeoffCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_msgs::TakeoffCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.altitude);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TakeoffCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_msgs::TakeoffCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_msgs::TakeoffCommand_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_MSGS_MESSAGE_TAKEOFFCOMMAND_H
