// Generated by gencpp from file uav_msgs/Target.msg
// DO NOT EDIT!


#ifndef UAV_MSGS_MESSAGE_TARGET_H
#define UAV_MSGS_MESSAGE_TARGET_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_msgs
{
template <class ContainerAllocator>
struct Target_
{
  typedef Target_<ContainerAllocator> Type;

  Target_()
    : cx(0.0)
    , cy(0.0)
    , w(0.0)
    , h(0.0)
    , score(0.0)
    , category()
    , category_id(0)
    , tracked_id(0)
    , px(0.0)
    , py(0.0)
    , pz(0.0)
    , los_ax(0.0)
    , los_ay(0.0)
    , yaw_a(0.0)
    , mode(false)
    , sim_score(0.0)  {
    }
  Target_(const ContainerAllocator& _alloc)
    : cx(0.0)
    , cy(0.0)
    , w(0.0)
    , h(0.0)
    , score(0.0)
    , category(_alloc)
    , category_id(0)
    , tracked_id(0)
    , px(0.0)
    , py(0.0)
    , pz(0.0)
    , los_ax(0.0)
    , los_ay(0.0)
    , yaw_a(0.0)
    , mode(false)
    , sim_score(0.0)  {
  (void)_alloc;
    }



   typedef float _cx_type;
  _cx_type cx;

   typedef float _cy_type;
  _cy_type cy;

   typedef float _w_type;
  _w_type w;

   typedef float _h_type;
  _h_type h;

   typedef float _score_type;
  _score_type score;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _category_type;
  _category_type category;

   typedef int32_t _category_id_type;
  _category_id_type category_id;

   typedef int32_t _tracked_id_type;
  _tracked_id_type tracked_id;

   typedef float _px_type;
  _px_type px;

   typedef float _py_type;
  _py_type py;

   typedef float _pz_type;
  _pz_type pz;

   typedef float _los_ax_type;
  _los_ax_type los_ax;

   typedef float _los_ay_type;
  _los_ay_type los_ay;

   typedef float _yaw_a_type;
  _yaw_a_type yaw_a;

   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef float _sim_score_type;
  _sim_score_type sim_score;





  typedef boost::shared_ptr< ::uav_msgs::Target_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_msgs::Target_<ContainerAllocator> const> ConstPtr;

}; // struct Target_

typedef ::uav_msgs::Target_<std::allocator<void> > Target;

typedef boost::shared_ptr< ::uav_msgs::Target > TargetPtr;
typedef boost::shared_ptr< ::uav_msgs::Target const> TargetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_msgs::Target_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_msgs::Target_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_msgs::Target_<ContainerAllocator1> & lhs, const ::uav_msgs::Target_<ContainerAllocator2> & rhs)
{
  return lhs.cx == rhs.cx &&
    lhs.cy == rhs.cy &&
    lhs.w == rhs.w &&
    lhs.h == rhs.h &&
    lhs.score == rhs.score &&
    lhs.category == rhs.category &&
    lhs.category_id == rhs.category_id &&
    lhs.tracked_id == rhs.tracked_id &&
    lhs.px == rhs.px &&
    lhs.py == rhs.py &&
    lhs.pz == rhs.pz &&
    lhs.los_ax == rhs.los_ax &&
    lhs.los_ay == rhs.los_ay &&
    lhs.yaw_a == rhs.yaw_a &&
    lhs.mode == rhs.mode &&
    lhs.sim_score == rhs.sim_score;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_msgs::Target_<ContainerAllocator1> & lhs, const ::uav_msgs::Target_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::Target_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::Target_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::Target_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::Target_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::Target_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::Target_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_msgs::Target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3623dd3b471832f212700e5baf3ce9ed";
  }

  static const char* value(const ::uav_msgs::Target_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3623dd3b471832f2ULL;
  static const uint64_t static_value2 = 0x12700e5baf3ce9edULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_msgs::Target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_msgs/Target";
  }

  static const char* value(const ::uav_msgs::Target_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_msgs::Target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"## 目标中心的水平位置 [0,1]\n"
"float32 cx\n"
"## 目标中心的垂直位置 [0,1]\n"
"float32 cy\n"
"\n"
"## 目标宽度/图像宽度 [0,1]\n"
"float32 w\n"
"## 目标高度/图像高度 [0,1]\n"
"float32 h\n"
"\n"
"## 目标置信度 [0,1]\n"
"float32 score\n"
"\n"
"## 目标类别名称\n"
"string category\n"
"## 目标类别编号 从0开始计算\n"
"int32 category_id\n"
"\n"
"## 目标跟踪ID号\n"
"int32 tracked_id\n"
"\n"
"## 目标3D位置 单位：m\n"
"float32 px\n"
"float32 py\n"
"float32 pz\n"
"\n"
"## 目标中心点的视线角度 [相机系下：右方x角度为正，下方y角度为正] 单位：度\n"
"float32 los_ax\n"
"float32 los_ay\n"
"\n"
"## 偏航角误差 [图像系下：垂直向上为0°，右半圈顺时针0~180°，左半圈逆时针0~-180°]\n"
"float32 yaw_a\n"
"\n"
"## detection(false/0) or tracked(true/1)\n"
"bool mode\n"
"\n"
"## CosineSimilarity\n"
"float32 sim_score\n"
"\n"
"\n"
"\n"
"\n"
;
  }

  static const char* value(const ::uav_msgs::Target_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_msgs::Target_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cx);
      stream.next(m.cy);
      stream.next(m.w);
      stream.next(m.h);
      stream.next(m.score);
      stream.next(m.category);
      stream.next(m.category_id);
      stream.next(m.tracked_id);
      stream.next(m.px);
      stream.next(m.py);
      stream.next(m.pz);
      stream.next(m.los_ax);
      stream.next(m.los_ay);
      stream.next(m.yaw_a);
      stream.next(m.mode);
      stream.next(m.sim_score);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Target_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_msgs::Target_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_msgs::Target_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "cx: ";
    Printer<float>::stream(s, indent + "  ", v.cx);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cy: ";
    Printer<float>::stream(s, indent + "  ", v.cy);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "w: ";
    Printer<float>::stream(s, indent + "  ", v.w);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "h: ";
    Printer<float>::stream(s, indent + "  ", v.h);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "score: ";
    Printer<float>::stream(s, indent + "  ", v.score);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "category: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.category);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "category_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.category_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tracked_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tracked_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "px: ";
    Printer<float>::stream(s, indent + "  ", v.px);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "py: ";
    Printer<float>::stream(s, indent + "  ", v.py);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pz: ";
    Printer<float>::stream(s, indent + "  ", v.pz);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "los_ax: ";
    Printer<float>::stream(s, indent + "  ", v.los_ax);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "los_ay: ";
    Printer<float>::stream(s, indent + "  ", v.los_ay);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw_a: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_a);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sim_score: ";
    Printer<float>::stream(s, indent + "  ", v.sim_score);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_MSGS_MESSAGE_TARGET_H
