// Generated by gencpp from file uav_msgs/UAVControlCommand.msg
// DO NOT EDIT!


#ifndef UAV_MSGS_MESSAGE_UAVCONTROLCOMMAND_H
#define UAV_MSGS_MESSAGE_UAVCONTROLCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <uav_msgs/TakeoffCommand.h>
#include <uav_msgs/LandCommand.h>
#include <uav_msgs/PositionControlNEDCommand.h>
#include <uav_msgs/PositionControlGlobalCommand.h>
#include <uav_msgs/VelocityControlNEDCommand.h>
#include <uav_msgs/ReturnToLaunchCommand.h>
#include <uav_msgs/HoverCommand.h>
#include <uav_msgs/SetModeCommand.h>
#include <uav_msgs/WaypointsCommand.h>

namespace uav_msgs
{
template <class ContainerAllocator>
struct UAVControlCommand_
{
  typedef UAVControlCommand_<ContainerAllocator> Type;

  UAVControlCommand_()
    : command_type()
    , timestamp()
    , target_system(0)
    , takeoff()
    , land()
    , pos_ned()
    , pos_global()
    , vel_ned()
    , rtl()
    , hover()
    , set_mode()
    , waypoints_cmd()  {
    }
  UAVControlCommand_(const ContainerAllocator& _alloc)
    : command_type(_alloc)
    , timestamp()
    , target_system(0)
    , takeoff(_alloc)
    , land(_alloc)
    , pos_ned(_alloc)
    , pos_global(_alloc)
    , vel_ned(_alloc)
    , rtl(_alloc)
    , hover(_alloc)
    , set_mode(_alloc)
    , waypoints_cmd(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _command_type_type;
  _command_type_type command_type;

   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef int32_t _target_system_type;
  _target_system_type target_system;

   typedef  ::uav_msgs::TakeoffCommand_<ContainerAllocator>  _takeoff_type;
  _takeoff_type takeoff;

   typedef  ::uav_msgs::LandCommand_<ContainerAllocator>  _land_type;
  _land_type land;

   typedef  ::uav_msgs::PositionControlNEDCommand_<ContainerAllocator>  _pos_ned_type;
  _pos_ned_type pos_ned;

   typedef  ::uav_msgs::PositionControlGlobalCommand_<ContainerAllocator>  _pos_global_type;
  _pos_global_type pos_global;

   typedef  ::uav_msgs::VelocityControlNEDCommand_<ContainerAllocator>  _vel_ned_type;
  _vel_ned_type vel_ned;

   typedef  ::uav_msgs::ReturnToLaunchCommand_<ContainerAllocator>  _rtl_type;
  _rtl_type rtl;

   typedef  ::uav_msgs::HoverCommand_<ContainerAllocator>  _hover_type;
  _hover_type hover;

   typedef  ::uav_msgs::SetModeCommand_<ContainerAllocator>  _set_mode_type;
  _set_mode_type set_mode;

   typedef  ::uav_msgs::WaypointsCommand_<ContainerAllocator>  _waypoints_cmd_type;
  _waypoints_cmd_type waypoints_cmd;





  typedef boost::shared_ptr< ::uav_msgs::UAVControlCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_msgs::UAVControlCommand_<ContainerAllocator> const> ConstPtr;

}; // struct UAVControlCommand_

typedef ::uav_msgs::UAVControlCommand_<std::allocator<void> > UAVControlCommand;

typedef boost::shared_ptr< ::uav_msgs::UAVControlCommand > UAVControlCommandPtr;
typedef boost::shared_ptr< ::uav_msgs::UAVControlCommand const> UAVControlCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_msgs::UAVControlCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_msgs::UAVControlCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_msgs::UAVControlCommand_<ContainerAllocator1> & lhs, const ::uav_msgs::UAVControlCommand_<ContainerAllocator2> & rhs)
{
  return lhs.command_type == rhs.command_type &&
    lhs.timestamp == rhs.timestamp &&
    lhs.target_system == rhs.target_system &&
    lhs.takeoff == rhs.takeoff &&
    lhs.land == rhs.land &&
    lhs.pos_ned == rhs.pos_ned &&
    lhs.pos_global == rhs.pos_global &&
    lhs.vel_ned == rhs.vel_ned &&
    lhs.rtl == rhs.rtl &&
    lhs.hover == rhs.hover &&
    lhs.set_mode == rhs.set_mode &&
    lhs.waypoints_cmd == rhs.waypoints_cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_msgs::UAVControlCommand_<ContainerAllocator1> & lhs, const ::uav_msgs::UAVControlCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::UAVControlCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::UAVControlCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::UAVControlCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::UAVControlCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::UAVControlCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::UAVControlCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_msgs::UAVControlCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1644fc0af173323746f79d8eb46fbc4";
  }

  static const char* value(const ::uav_msgs::UAVControlCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1644fc0af173323ULL;
  static const uint64_t static_value2 = 0x746f79d8eb46fbc4ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_msgs::UAVControlCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_msgs/UAVControlCommand";
  }

  static const char* value(const ::uav_msgs::UAVControlCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_msgs::UAVControlCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"string command_type\n"
"time timestamp\n"
"int32 target_system\n"
"\n"
"TakeoffCommand takeoff\n"
"LandCommand land\n"
"PositionControlNEDCommand pos_ned\n"
"PositionControlGlobalCommand pos_global\n"
"VelocityControlNEDCommand vel_ned\n"
"ReturnToLaunchCommand rtl\n"
"HoverCommand hover\n"
"SetModeCommand set_mode\n"
"WaypointsCommand waypoints_cmd\n"
"\n"
"================================================================================\n"
"MSG: uav_msgs/TakeoffCommand\n"
"float64 altitude\n"
"float64 yaw\n"
"\n"
"================================================================================\n"
"MSG: uav_msgs/LandCommand\n"
"float64 yaw\n"
"\n"
"================================================================================\n"
"MSG: uav_msgs/PositionControlNEDCommand\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 yaw\n"
"\n"
"================================================================================\n"
"MSG: uav_msgs/PositionControlGlobalCommand\n"
"float64 latitude\n"
"float64 longitude\n"
"float64 altitude\n"
"float64 yaw\n"
"\n"
"================================================================================\n"
"MSG: uav_msgs/VelocityControlNEDCommand\n"
"float64 vx\n"
"float64 vy\n"
"float64 vz\n"
"float64 yaw_rate\n"
"\n"
"================================================================================\n"
"MSG: uav_msgs/ReturnToLaunchCommand\n"
"float64 altitude\n"
"\n"
"================================================================================\n"
"MSG: uav_msgs/HoverCommand\n"
"string mode\n"
"================================================================================\n"
"MSG: uav_msgs/SetModeCommand\n"
"string mode\n"
"\n"
"================================================================================\n"
"MSG: uav_msgs/WaypointsCommand\n"
"bool clear_existing      #是否清除存在航线\n"
"Waypoint[] waypoints       # 航点列表\n"
"================================================================================\n"
"MSG: uav_msgs/Waypoint\n"
"int32 waypoint_id\n"
"mavros_msgs/Waypoint waypoint\n"
"\n"
"================================================================================\n"
"MSG: mavros_msgs/Waypoint\n"
"# Waypoint.msg\n"
"#\n"
"# ROS representation of MAVLink MISSION_ITEM\n"
"# See mavlink documentation\n"
"\n"
"\n"
"\n"
"# see enum MAV_FRAME\n"
"uint8 frame\n"
"uint8 FRAME_GLOBAL = 0\n"
"uint8 FRAME_LOCAL_NED = 1\n"
"uint8 FRAME_MISSION = 2\n"
"uint8 FRAME_GLOBAL_REL_ALT = 3\n"
"uint8 FRAME_LOCAL_ENU = 4\n"
"uint8 FRAME_GLOBAL_INT = 5\n"
"uint8 FRAME_GLOBAL_RELATIVE_ALT_INT = 6\n"
"uint8 FRAME_LOCAL_OFFSET_NED = 7\n"
"uint8 FRAME_BODY_NED = 8\n"
"uint8 FRAME_BODY_OFFSET_NED = 9\n"
"uint8 FRAME_GLOBAL_TERRAIN_ALT = 10\n"
"uint8 FRAME_GLOBAL_TERRAIN_ALT_INT = 11\n"
"uint8 FRAME_BODY_FRD = 12\n"
"uint8 FRAME_RESERVED_13 = 13\n"
"uint8 FRAME_RESERVED_14 = 14\n"
"uint8 FRAME_RESERVED_15 = 15\n"
"uint8 FRAME_RESERVED_16 = 16\n"
"uint8 FRAME_RESERVED_17 = 17\n"
"uint8 FRAME_RESERVED_18 = 18\n"
"uint8 FRAME_RESERVED_19 = 19\n"
"uint8 FRAME_LOCAL_FRD = 20\n"
"uint8 FRAME_LOCAL_FLU = 21\n"
"\n"
"# see enum MAV_CMD and CommandCode.msg\n"
"uint16 command\n"
"\n"
"bool is_current\n"
"bool autocontinue\n"
"# meaning of this params described in enum MAV_CMD\n"
"float32 param1\n"
"float32 param2\n"
"float32 param3\n"
"float32 param4\n"
"float64 x_lat\n"
"float64 y_long\n"
"float64 z_alt\n"
;
  }

  static const char* value(const ::uav_msgs::UAVControlCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_msgs::UAVControlCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command_type);
      stream.next(m.timestamp);
      stream.next(m.target_system);
      stream.next(m.takeoff);
      stream.next(m.land);
      stream.next(m.pos_ned);
      stream.next(m.pos_global);
      stream.next(m.vel_ned);
      stream.next(m.rtl);
      stream.next(m.hover);
      stream.next(m.set_mode);
      stream.next(m.waypoints_cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UAVControlCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_msgs::UAVControlCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_msgs::UAVControlCommand_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "command_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.command_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_system: ";
    Printer<int32_t>::stream(s, indent + "  ", v.target_system);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "takeoff: ";
    Printer< ::uav_msgs::TakeoffCommand_<ContainerAllocator> >::stream(s, indent + "  ", v.takeoff);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "land: ";
    Printer< ::uav_msgs::LandCommand_<ContainerAllocator> >::stream(s, indent + "  ", v.land);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pos_ned: ";
    Printer< ::uav_msgs::PositionControlNEDCommand_<ContainerAllocator> >::stream(s, indent + "  ", v.pos_ned);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pos_global: ";
    Printer< ::uav_msgs::PositionControlGlobalCommand_<ContainerAllocator> >::stream(s, indent + "  ", v.pos_global);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vel_ned: ";
    Printer< ::uav_msgs::VelocityControlNEDCommand_<ContainerAllocator> >::stream(s, indent + "  ", v.vel_ned);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rtl: ";
    Printer< ::uav_msgs::ReturnToLaunchCommand_<ContainerAllocator> >::stream(s, indent + "  ", v.rtl);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "hover: ";
    Printer< ::uav_msgs::HoverCommand_<ContainerAllocator> >::stream(s, indent + "  ", v.hover);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "set_mode: ";
    Printer< ::uav_msgs::SetModeCommand_<ContainerAllocator> >::stream(s, indent + "  ", v.set_mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "waypoints_cmd: ";
    Printer< ::uav_msgs::WaypointsCommand_<ContainerAllocator> >::stream(s, indent + "  ", v.waypoints_cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_MSGS_MESSAGE_UAVCONTROLCOMMAND_H
