// Generated by gencpp from file uav_msgs/VelocityControlNEDCommand.msg
// DO NOT EDIT!


#ifndef UAV_MSGS_MESSAGE_VELOCITYCONTROLNEDCOMMAND_H
#define UAV_MSGS_MESSAGE_VELOCITYCONTROLNEDCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_msgs
{
template <class ContainerAllocator>
struct VelocityControlNEDCommand_
{
  typedef VelocityControlNEDCommand_<ContainerAllocator> Type;

  VelocityControlNEDCommand_()
    : vx(0.0)
    , vy(0.0)
    , vz(0.0)
    , yaw_rate(0.0)  {
    }
  VelocityControlNEDCommand_(const ContainerAllocator& _alloc)
    : vx(0.0)
    , vy(0.0)
    , vz(0.0)
    , yaw_rate(0.0)  {
  (void)_alloc;
    }



   typedef double _vx_type;
  _vx_type vx;

   typedef double _vy_type;
  _vy_type vy;

   typedef double _vz_type;
  _vz_type vz;

   typedef double _yaw_rate_type;
  _yaw_rate_type yaw_rate;





  typedef boost::shared_ptr< ::uav_msgs::VelocityControlNEDCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_msgs::VelocityControlNEDCommand_<ContainerAllocator> const> ConstPtr;

}; // struct VelocityControlNEDCommand_

typedef ::uav_msgs::VelocityControlNEDCommand_<std::allocator<void> > VelocityControlNEDCommand;

typedef boost::shared_ptr< ::uav_msgs::VelocityControlNEDCommand > VelocityControlNEDCommandPtr;
typedef boost::shared_ptr< ::uav_msgs::VelocityControlNEDCommand const> VelocityControlNEDCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_msgs::VelocityControlNEDCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_msgs::VelocityControlNEDCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_msgs::VelocityControlNEDCommand_<ContainerAllocator1> & lhs, const ::uav_msgs::VelocityControlNEDCommand_<ContainerAllocator2> & rhs)
{
  return lhs.vx == rhs.vx &&
    lhs.vy == rhs.vy &&
    lhs.vz == rhs.vz &&
    lhs.yaw_rate == rhs.yaw_rate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_msgs::VelocityControlNEDCommand_<ContainerAllocator1> & lhs, const ::uav_msgs::VelocityControlNEDCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::VelocityControlNEDCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::VelocityControlNEDCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::VelocityControlNEDCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::VelocityControlNEDCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::VelocityControlNEDCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::VelocityControlNEDCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_msgs::VelocityControlNEDCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4b632edbf148b4de86917df6b3e0c126";
  }

  static const char* value(const ::uav_msgs::VelocityControlNEDCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4b632edbf148b4deULL;
  static const uint64_t static_value2 = 0x86917df6b3e0c126ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_msgs::VelocityControlNEDCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_msgs/VelocityControlNEDCommand";
  }

  static const char* value(const ::uav_msgs::VelocityControlNEDCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_msgs::VelocityControlNEDCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 vx\n"
"float64 vy\n"
"float64 vz\n"
"float64 yaw_rate\n"
;
  }

  static const char* value(const ::uav_msgs::VelocityControlNEDCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_msgs::VelocityControlNEDCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.vz);
      stream.next(m.yaw_rate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelocityControlNEDCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_msgs::VelocityControlNEDCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_msgs::VelocityControlNEDCommand_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "vx: ";
    Printer<double>::stream(s, indent + "  ", v.vx);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vy: ";
    Printer<double>::stream(s, indent + "  ", v.vy);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vz: ";
    Printer<double>::stream(s, indent + "  ", v.vz);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw_rate: ";
    Printer<double>::stream(s, indent + "  ", v.yaw_rate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_MSGS_MESSAGE_VELOCITYCONTROLNEDCOMMAND_H
