// Generated by gencpp from file uav_msgs/WaypointsCommand.msg
// DO NOT EDIT!


#ifndef UAV_MSGS_MESSAGE_WAYPOINTSCOMMAND_H
#define UAV_MSGS_MESSAGE_WAYPOINTSCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <uav_msgs/Waypoint.h>

namespace uav_msgs
{
template <class ContainerAllocator>
struct WaypointsCommand_
{
  typedef WaypointsCommand_<ContainerAllocator> Type;

  WaypointsCommand_()
    : start_immediately(false)
    , waypoints()  {
    }
  WaypointsCommand_(const ContainerAllocator& _alloc)
    : start_immediately(false)
    , waypoints(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _start_immediately_type;
  _start_immediately_type start_immediately;

   typedef std::vector< ::uav_msgs::Waypoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::uav_msgs::Waypoint_<ContainerAllocator> >> _waypoints_type;
  _waypoints_type waypoints;





  typedef boost::shared_ptr< ::uav_msgs::WaypointsCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_msgs::WaypointsCommand_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointsCommand_

typedef ::uav_msgs::WaypointsCommand_<std::allocator<void> > WaypointsCommand;

typedef boost::shared_ptr< ::uav_msgs::WaypointsCommand > WaypointsCommandPtr;
typedef boost::shared_ptr< ::uav_msgs::WaypointsCommand const> WaypointsCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_msgs::WaypointsCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_msgs::WaypointsCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_msgs::WaypointsCommand_<ContainerAllocator1> & lhs, const ::uav_msgs::WaypointsCommand_<ContainerAllocator2> & rhs)
{
  return lhs.start_immediately == rhs.start_immediately &&
    lhs.waypoints == rhs.waypoints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_msgs::WaypointsCommand_<ContainerAllocator1> & lhs, const ::uav_msgs::WaypointsCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::WaypointsCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::WaypointsCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::WaypointsCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::WaypointsCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::WaypointsCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::WaypointsCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_msgs::WaypointsCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dca3761828b95042e94f1dee6fa350dd";
  }

  static const char* value(const ::uav_msgs::WaypointsCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdca3761828b95042ULL;
  static const uint64_t static_value2 = 0xe94f1dee6fa350ddULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_msgs::WaypointsCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_msgs/WaypointsCommand";
  }

  static const char* value(const ::uav_msgs::WaypointsCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_msgs::WaypointsCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool start_immediately     # 是否立即执行航点\n"
"Waypoint[] waypoints       # 航点列表\n"
"================================================================================\n"
"MSG: uav_msgs/Waypoint\n"
"int32 waypoint_id          # 航点ID\n"
"string frame               # 坐标系类型\n"
"string command             # 航点指令类型\n"
"float64 latitude           # 纬度 (度)\n"
"float64 longitude          # 经度 (度)\n"
"float64 altitude           # 高度 (米)\n"
"bool is_current            # 是否为当前航点\n"
"bool autocontinue          # 是否自动继续到下一个航点\n"
"float64 hold_time          # 悬停时间 (秒)\n"
;
  }

  static const char* value(const ::uav_msgs::WaypointsCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_msgs::WaypointsCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start_immediately);
      stream.next(m.waypoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointsCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_msgs::WaypointsCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_msgs::WaypointsCommand_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "start_immediately: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start_immediately);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "waypoints: ";
    if (v.waypoints.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.waypoints.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::uav_msgs::Waypoint_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.waypoints[i]);
    }
    if (v.waypoints.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_MSGS_MESSAGE_WAYPOINTSCOMMAND_H
