// Generated by gencpp from file uav_msgs/Waypoint.msg
// DO NOT EDIT!


#ifndef UAV_MSGS_MESSAGE_WAYPOINT_H
#define UAV_MSGS_MESSAGE_WAYPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_msgs
{
template <class ContainerAllocator>
struct Waypoint_
{
  typedef Waypoint_<ContainerAllocator> Type;

  Waypoint_()
    : waypoint_id(0)
    , frame()
    , command()
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , is_current(false)
    , autocontinue(false)
    , hold_time(0.0)  {
    }
  Waypoint_(const ContainerAllocator& _alloc)
    : waypoint_id(0)
    , frame(_alloc)
    , command(_alloc)
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , is_current(false)
    , autocontinue(false)
    , hold_time(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _waypoint_id_type;
  _waypoint_id_type waypoint_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _frame_type;
  _frame_type frame;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _command_type;
  _command_type command;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _altitude_type;
  _altitude_type altitude;

   typedef uint8_t _is_current_type;
  _is_current_type is_current;

   typedef uint8_t _autocontinue_type;
  _autocontinue_type autocontinue;

   typedef double _hold_time_type;
  _hold_time_type hold_time;





  typedef boost::shared_ptr< ::uav_msgs::Waypoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_msgs::Waypoint_<ContainerAllocator> const> ConstPtr;

}; // struct Waypoint_

typedef ::uav_msgs::Waypoint_<std::allocator<void> > Waypoint;

typedef boost::shared_ptr< ::uav_msgs::Waypoint > WaypointPtr;
typedef boost::shared_ptr< ::uav_msgs::Waypoint const> WaypointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_msgs::Waypoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_msgs::Waypoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_msgs::Waypoint_<ContainerAllocator1> & lhs, const ::uav_msgs::Waypoint_<ContainerAllocator2> & rhs)
{
  return lhs.waypoint_id == rhs.waypoint_id &&
    lhs.frame == rhs.frame &&
    lhs.command == rhs.command &&
    lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.altitude == rhs.altitude &&
    lhs.is_current == rhs.is_current &&
    lhs.autocontinue == rhs.autocontinue &&
    lhs.hold_time == rhs.hold_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_msgs::Waypoint_<ContainerAllocator1> & lhs, const ::uav_msgs::Waypoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::Waypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::Waypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::Waypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::Waypoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::Waypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::Waypoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_msgs::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d3f2cf73442657b7c4a745798b838c76";
  }

  static const char* value(const ::uav_msgs::Waypoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd3f2cf73442657b7ULL;
  static const uint64_t static_value2 = 0xc4a745798b838c76ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_msgs::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_msgs/Waypoint";
  }

  static const char* value(const ::uav_msgs::Waypoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_msgs::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 waypoint_id          # 航点ID\n"
"string frame               # 坐标系类型\n"
"string command             # 航点指令类型\n"
"float64 latitude           # 纬度 (度)\n"
"float64 longitude          # 经度 (度)\n"
"float64 altitude           # 高度 (米)\n"
"bool is_current            # 是否为当前航点\n"
"bool autocontinue          # 是否自动继续到下一个航点\n"
"float64 hold_time          # 悬停时间 (秒)\n"
;
  }

  static const char* value(const ::uav_msgs::Waypoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_msgs::Waypoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypoint_id);
      stream.next(m.frame);
      stream.next(m.command);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
      stream.next(m.is_current);
      stream.next(m.autocontinue);
      stream.next(m.hold_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Waypoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_msgs::Waypoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_msgs::Waypoint_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "waypoint_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.waypoint_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.frame);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.command);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "is_current: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_current);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "autocontinue: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.autocontinue);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "hold_time: ";
    Printer<double>::stream(s, indent + "  ", v.hold_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_MSGS_MESSAGE_WAYPOINT_H
