// Generated by gencpp from file uav_msgs/WaypointsCommand.msg
// DO NOT EDIT!


#ifndef UAV_MSGS_MESSAGE_WAYPOINTSCOMMAND_H
#define UAV_MSGS_MESSAGE_WAYPOINTSCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <uav_msgs/Waypoint.h>

namespace uav_msgs
{
template <class ContainerAllocator>
struct WaypointsCommand_
{
  typedef WaypointsCommand_<ContainerAllocator> Type;

  WaypointsCommand_()
    : clear_existing(false)
    , waypoints()  {
    }
  WaypointsCommand_(const ContainerAllocator& _alloc)
    : clear_existing(false)
    , waypoints(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _clear_existing_type;
  _clear_existing_type clear_existing;

   typedef std::vector< ::uav_msgs::Waypoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::uav_msgs::Waypoint_<ContainerAllocator> >> _waypoints_type;
  _waypoints_type waypoints;





  typedef boost::shared_ptr< ::uav_msgs::WaypointsCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_msgs::WaypointsCommand_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointsCommand_

typedef ::uav_msgs::WaypointsCommand_<std::allocator<void> > WaypointsCommand;

typedef boost::shared_ptr< ::uav_msgs::WaypointsCommand > WaypointsCommandPtr;
typedef boost::shared_ptr< ::uav_msgs::WaypointsCommand const> WaypointsCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_msgs::WaypointsCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_msgs::WaypointsCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_msgs::WaypointsCommand_<ContainerAllocator1> & lhs, const ::uav_msgs::WaypointsCommand_<ContainerAllocator2> & rhs)
{
  return lhs.clear_existing == rhs.clear_existing &&
    lhs.waypoints == rhs.waypoints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_msgs::WaypointsCommand_<ContainerAllocator1> & lhs, const ::uav_msgs::WaypointsCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::WaypointsCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::WaypointsCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::WaypointsCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::WaypointsCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::WaypointsCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::WaypointsCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_msgs::WaypointsCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "64dffdfd8bd5405e375d970e627fb6dc";
  }

  static const char* value(const ::uav_msgs::WaypointsCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x64dffdfd8bd5405eULL;
  static const uint64_t static_value2 = 0x375d970e627fb6dcULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_msgs::WaypointsCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_msgs/WaypointsCommand";
  }

  static const char* value(const ::uav_msgs::WaypointsCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_msgs::WaypointsCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool clear_existing      #是否清除存在航线\n"
"Waypoint[] waypoints       # 航点列表\n"
"================================================================================\n"
"MSG: uav_msgs/Waypoint\n"
"int32 waypoint_id\n"
"mavros_msgs/Waypoint waypoint\n"
"\n"
"================================================================================\n"
"MSG: mavros_msgs/Waypoint\n"
"# Waypoint.msg\n"
"#\n"
"# ROS representation of MAVLink MISSION_ITEM\n"
"# See mavlink documentation\n"
"\n"
"\n"
"\n"
"# see enum MAV_FRAME\n"
"uint8 frame\n"
"uint8 FRAME_GLOBAL = 0\n"
"uint8 FRAME_LOCAL_NED = 1\n"
"uint8 FRAME_MISSION = 2\n"
"uint8 FRAME_GLOBAL_REL_ALT = 3\n"
"uint8 FRAME_LOCAL_ENU = 4\n"
"uint8 FRAME_GLOBAL_INT = 5\n"
"uint8 FRAME_GLOBAL_RELATIVE_ALT_INT = 6\n"
"uint8 FRAME_LOCAL_OFFSET_NED = 7\n"
"uint8 FRAME_BODY_NED = 8\n"
"uint8 FRAME_BODY_OFFSET_NED = 9\n"
"uint8 FRAME_GLOBAL_TERRAIN_ALT = 10\n"
"uint8 FRAME_GLOBAL_TERRAIN_ALT_INT = 11\n"
"uint8 FRAME_BODY_FRD = 12\n"
"uint8 FRAME_RESERVED_13 = 13\n"
"uint8 FRAME_RESERVED_14 = 14\n"
"uint8 FRAME_RESERVED_15 = 15\n"
"uint8 FRAME_RESERVED_16 = 16\n"
"uint8 FRAME_RESERVED_17 = 17\n"
"uint8 FRAME_RESERVED_18 = 18\n"
"uint8 FRAME_RESERVED_19 = 19\n"
"uint8 FRAME_LOCAL_FRD = 20\n"
"uint8 FRAME_LOCAL_FLU = 21\n"
"\n"
"# see enum MAV_CMD and CommandCode.msg\n"
"uint16 command\n"
"\n"
"bool is_current\n"
"bool autocontinue\n"
"# meaning of this params described in enum MAV_CMD\n"
"float32 param1\n"
"float32 param2\n"
"float32 param3\n"
"float32 param4\n"
"float64 x_lat\n"
"float64 y_long\n"
"float64 z_alt\n"
;
  }

  static const char* value(const ::uav_msgs::WaypointsCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_msgs::WaypointsCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.clear_existing);
      stream.next(m.waypoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointsCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_msgs::WaypointsCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_msgs::WaypointsCommand_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "clear_existing: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.clear_existing);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "waypoints: ";
    if (v.waypoints.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.waypoints.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::uav_msgs::Waypoint_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.waypoints[i]);
    }
    if (v.waypoints.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_MSGS_MESSAGE_WAYPOINTSCOMMAND_H
