// Generated by gencpp from file px_uav_msgs/MultiUGVState.msg
// DO NOT EDIT!


#ifndef PX_UAV_MSGS_MESSAGE_MULTIUGVSTATE_H
#define PX_UAV_MSGS_MESSAGE_MULTIUGVSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <px_uav_msgs/UGVState.h>

namespace px_uav_msgs
{
template <class ContainerAllocator>
struct MultiUGVState_
{
  typedef MultiUGVState_<ContainerAllocator> Type;

  MultiUGVState_()
    : header()
    , swarm_num_ugv(0)
    , ugv_state_all()  {
    }
  MultiUGVState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , swarm_num_ugv(0)
    , ugv_state_all(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _swarm_num_ugv_type;
  _swarm_num_ugv_type swarm_num_ugv;

   typedef std::vector< ::px_uav_msgs::UGVState_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::px_uav_msgs::UGVState_<ContainerAllocator> >> _ugv_state_all_type;
  _ugv_state_all_type ugv_state_all;





  typedef boost::shared_ptr< ::px_uav_msgs::MultiUGVState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px_uav_msgs::MultiUGVState_<ContainerAllocator> const> ConstPtr;

}; // struct MultiUGVState_

typedef ::px_uav_msgs::MultiUGVState_<std::allocator<void> > MultiUGVState;

typedef boost::shared_ptr< ::px_uav_msgs::MultiUGVState > MultiUGVStatePtr;
typedef boost::shared_ptr< ::px_uav_msgs::MultiUGVState const> MultiUGVStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px_uav_msgs::MultiUGVState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px_uav_msgs::MultiUGVState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px_uav_msgs::MultiUGVState_<ContainerAllocator1> & lhs, const ::px_uav_msgs::MultiUGVState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.swarm_num_ugv == rhs.swarm_num_ugv &&
    lhs.ugv_state_all == rhs.ugv_state_all;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px_uav_msgs::MultiUGVState_<ContainerAllocator1> & lhs, const ::px_uav_msgs::MultiUGVState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px_uav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px_uav_msgs::MultiUGVState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px_uav_msgs::MultiUGVState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px_uav_msgs::MultiUGVState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px_uav_msgs::MultiUGVState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px_uav_msgs::MultiUGVState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px_uav_msgs::MultiUGVState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px_uav_msgs::MultiUGVState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a186972accb0af8d487fa5c5c2db7013";
  }

  static const char* value(const ::px_uav_msgs::MultiUGVState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa186972accb0af8dULL;
  static const uint64_t static_value2 = 0x487fa5c5c2db7013ULL;
};

template<class ContainerAllocator>
struct DataType< ::px_uav_msgs::MultiUGVState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px_uav_msgs/MultiUGVState";
  }

  static const char* value(const ::px_uav_msgs::MultiUGVState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px_uav_msgs::MultiUGVState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"## \n"
"int32 swarm_num_ugv\n"
"\n"
"## 从1开始\n"
"UGVState[] ugv_state_all\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: px_uav_msgs/UGVState\n"
"std_msgs/Header header\n"
"\n"
"## 无人机编号\n"
"uint8 ugv_id\n"
"\n"
"## 电池电量\n"
"float32 battery\n"
"\n"
"## 无人机状态量：位置、速度、姿态\n"
"float32[3] position                 ## [m]\n"
"float32[3] velocity                 ## [m/s]\n"
"float32[3] attitude                 ## [rad]\n"
"\n"
"geometry_msgs/Quaternion attitude_q ## 四元数\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::px_uav_msgs::MultiUGVState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px_uav_msgs::MultiUGVState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.swarm_num_ugv);
      stream.next(m.ugv_state_all);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiUGVState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px_uav_msgs::MultiUGVState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px_uav_msgs::MultiUGVState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "swarm_num_ugv: ";
    Printer<int32_t>::stream(s, indent + "  ", v.swarm_num_ugv);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ugv_state_all: ";
    if (v.ugv_state_all.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.ugv_state_all.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::px_uav_msgs::UGVState_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.ugv_state_all[i]);
    }
    if (v.ugv_state_all.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX_UAV_MSGS_MESSAGE_MULTIUGVSTATE_H
