// Generated by gencpp from file px_uav_msgs/TargetsInFrame.msg
// DO NOT EDIT!


#ifndef PX_UAV_MSGS_MESSAGE_TARGETSINFRAME_H
#define PX_UAV_MSGS_MESSAGE_TARGETSINFRAME_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <px_uav_msgs/Target.h>
#include <px_uav_msgs/ROI.h>

namespace px_uav_msgs
{
template <class ContainerAllocator>
struct TargetsInFrame_
{
  typedef TargetsInFrame_<ContainerAllocator> Type;

  TargetsInFrame_()
    : header()
    , frame_id(0)
    , height(0)
    , width(0)
    , fps(0.0)
    , fov_x(0.0)
    , fov_y(0.0)
    , targets()
    , rois()
    , no_track_frame_count(0)
    , tracking_state(false)  {
    }
  TargetsInFrame_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , frame_id(0)
    , height(0)
    , width(0)
    , fps(0.0)
    , fov_x(0.0)
    , fov_y(0.0)
    , targets(_alloc)
    , rois(_alloc)
    , no_track_frame_count(0)
    , tracking_state(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _frame_id_type;
  _frame_id_type frame_id;

   typedef int32_t _height_type;
  _height_type height;

   typedef int32_t _width_type;
  _width_type width;

   typedef float _fps_type;
  _fps_type fps;

   typedef float _fov_x_type;
  _fov_x_type fov_x;

   typedef float _fov_y_type;
  _fov_y_type fov_y;

   typedef std::vector< ::px_uav_msgs::Target_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::px_uav_msgs::Target_<ContainerAllocator> >> _targets_type;
  _targets_type targets;

   typedef std::vector< ::px_uav_msgs::ROI_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::px_uav_msgs::ROI_<ContainerAllocator> >> _rois_type;
  _rois_type rois;

   typedef int32_t _no_track_frame_count_type;
  _no_track_frame_count_type no_track_frame_count;

   typedef uint8_t _tracking_state_type;
  _tracking_state_type tracking_state;





  typedef boost::shared_ptr< ::px_uav_msgs::TargetsInFrame_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::px_uav_msgs::TargetsInFrame_<ContainerAllocator> const> ConstPtr;

}; // struct TargetsInFrame_

typedef ::px_uav_msgs::TargetsInFrame_<std::allocator<void> > TargetsInFrame;

typedef boost::shared_ptr< ::px_uav_msgs::TargetsInFrame > TargetsInFramePtr;
typedef boost::shared_ptr< ::px_uav_msgs::TargetsInFrame const> TargetsInFrameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::px_uav_msgs::TargetsInFrame_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::px_uav_msgs::TargetsInFrame_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::px_uav_msgs::TargetsInFrame_<ContainerAllocator1> & lhs, const ::px_uav_msgs::TargetsInFrame_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.frame_id == rhs.frame_id &&
    lhs.height == rhs.height &&
    lhs.width == rhs.width &&
    lhs.fps == rhs.fps &&
    lhs.fov_x == rhs.fov_x &&
    lhs.fov_y == rhs.fov_y &&
    lhs.targets == rhs.targets &&
    lhs.rois == rhs.rois &&
    lhs.no_track_frame_count == rhs.no_track_frame_count &&
    lhs.tracking_state == rhs.tracking_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::px_uav_msgs::TargetsInFrame_<ContainerAllocator1> & lhs, const ::px_uav_msgs::TargetsInFrame_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace px_uav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::px_uav_msgs::TargetsInFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::px_uav_msgs::TargetsInFrame_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px_uav_msgs::TargetsInFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::px_uav_msgs::TargetsInFrame_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px_uav_msgs::TargetsInFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::px_uav_msgs::TargetsInFrame_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::px_uav_msgs::TargetsInFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "50723d8130f9d56db1f6a8f8b5c9622c";
  }

  static const char* value(const ::px_uav_msgs::TargetsInFrame_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x50723d8130f9d56dULL;
  static const uint64_t static_value2 = 0xb1f6a8f8b5c9622cULL;
};

template<class ContainerAllocator>
struct DataType< ::px_uav_msgs::TargetsInFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "px_uav_msgs/TargetsInFrame";
  }

  static const char* value(const ::px_uav_msgs::TargetsInFrame_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::px_uav_msgs::TargetsInFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "## ROS Header\n"
"std_msgs/Header header\n"
"\n"
"## 帧ID号\n"
"int32 frame_id\n"
"\n"
"## 帧像素高度\n"
"int32 height\n"
"## 帧像素宽度\n"
"int32 width\n"
"\n"
"## 当前检测/跟踪频率\n"
"float32 fps\n"
"\n"
"## 当前成像设备的水平视场角，单位：度\n"
"float32 fov_x\n"
"## 当前成像设备的垂直视场角，单位：度\n"
"float32 fov_y\n"
"\n"
"## 当前帧每个目标信息\n"
"Target[] targets\n"
"\n"
"## 当前检测的兴趣区域，ROIs\n"
"ROI[] rois\n"
"\n"
"##focusing solely on tracking , without considering detection\n"
"int32 no_track_frame_count\n"
"\n"
"## 是否处于跟踪状态，0：否，1：是。当状态为1，targets为空表示丢失；targets不为空表示正常跟踪。\n"
"bool tracking_state\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: px_uav_msgs/Target\n"
"\n"
"## 目标中心的水平位置 [0,1]\n"
"float32 cx\n"
"## 目标中心的垂直位置 [0,1]\n"
"float32 cy\n"
"\n"
"## 目标宽度/图像宽度 [0,1]\n"
"float32 w\n"
"## 目标高度/图像高度 [0,1]\n"
"float32 h\n"
"\n"
"## 目标置信度 [0,1]\n"
"float32 score\n"
"\n"
"## 目标类别名称\n"
"string category\n"
"## 目标类别编号 从0开始计算\n"
"int32 category_id\n"
"\n"
"## 目标跟踪ID号\n"
"int32 tracked_id\n"
"\n"
"## 目标3D位置 单位：m\n"
"float32 px\n"
"float32 py\n"
"float32 pz\n"
"\n"
"## 目标中心点的视线角度 [相机系下：右方x角度为正，下方y角度为正] 单位：度\n"
"float32 los_ax\n"
"float32 los_ay\n"
"\n"
"## 偏航角误差 [图像系下：垂直向上为0°，右半圈顺时针0~180°，左半圈逆时针0~-180°]\n"
"float32 yaw_a\n"
"\n"
"## detection(false/0) or tracked(true/1)\n"
"bool mode\n"
"\n"
"## CosineSimilarity\n"
"float32 sim_score\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: px_uav_msgs/ROI\n"
"\n"
"## 区域左上角像素坐标\n"
"int32 x1\n"
"int32 y1\n"
"\n"
"## 区域右下角像素坐标\n"
"int32 x2\n"
"int32 y2\n"
;
  }

  static const char* value(const ::px_uav_msgs::TargetsInFrame_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::px_uav_msgs::TargetsInFrame_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.frame_id);
      stream.next(m.height);
      stream.next(m.width);
      stream.next(m.fps);
      stream.next(m.fov_x);
      stream.next(m.fov_y);
      stream.next(m.targets);
      stream.next(m.rois);
      stream.next(m.no_track_frame_count);
      stream.next(m.tracking_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TargetsInFrame_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::px_uav_msgs::TargetsInFrame_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::px_uav_msgs::TargetsInFrame_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "frame_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.frame_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.width);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fps: ";
    Printer<float>::stream(s, indent + "  ", v.fps);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fov_x: ";
    Printer<float>::stream(s, indent + "  ", v.fov_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fov_y: ";
    Printer<float>::stream(s, indent + "  ", v.fov_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "targets: ";
    if (v.targets.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.targets.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::px_uav_msgs::Target_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.targets[i]);
    }
    if (v.targets.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rois: ";
    if (v.rois.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.rois.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::px_uav_msgs::ROI_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.rois[i]);
    }
    if (v.rois.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "no_track_frame_count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.no_track_frame_count);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tracking_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tracking_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PX_UAV_MSGS_MESSAGE_TARGETSINFRAME_H
