(cl:in-package px_uav_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          UAV_ID-VAL
          UAV_ID
          CONNECTED-VAL
          CONNECTED
          ARMED-VAL
          ARMED
          MODE-VAL
          MODE
          LOCATION_SOURCE-VAL
          LOCATION_SOURCE
          ODOM_VALID-VAL
          ODOM_VALID
          GPS_STATUS-VAL
          GPS_STATUS
          GPS_NUM-VAL
          GPS_NUM
          POSITION-VAL
          POSITION
          RANGE-VAL
          RANGE
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          REL_ALT-VAL
          REL_ALT
          VELOCITY-VAL
          VELOCITY
          ATTITUDE-VAL
          ATTITUDE
          ATTITUDE_Q-VAL
          ATTITUDE_Q
          ATTITUDE_RATE-VAL
          ATTITUDE_RATE
          BATTERY_STATE-VAL
          BATTERY_STATE
          BATTERY_PERCETAGE-VAL
          BATTERY_PERCETAGE
))