(cl:in-package px_uav_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          AGENT_CMD-VAL
          AGENT_CMD
          CONTROL_LEVEL-VAL
          CONTROL_LEVEL
          MOVE_MODE-VAL
          MOVE_MODE
          POSITION_REF-VAL
          POSITION_REF
          VELOCITY_REF-VAL
          VELOCITY_REF
          ACCELERATION_REF-VAL
          ACCELERATION_REF
          YAW_REF-VAL
          YAW_REF
          YAW_RATE_MODE-VAL
          YAW_RATE_MODE
          YAW_RATE_REF-VAL
          YAW_RATE_REF
          ATT_REF-VAL
          ATT_REF
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          COMMAND_ID-VAL
          COMMAND_ID
))