(cl:in-package px_uav_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SOURCE-VAL
          SOURCE
          SWARM_NUM-VAL
          SWARM_NUM
          SWARM_LOCATION_SOURCE-VAL
          SWARM_LOCATION_SOURCE
          SWARM_CMD-VAL
          SWARM_CMD
          LEADER_POS-VAL
          LEADER_POS
          LEADER_VEL-VAL
          LEADER_VEL
          SWARM_SIZE-VAL
          SWARM_SIZE
          SWARM_SHAPE-VAL
          SWARM_SHAPE
          TARGET_AREA_X_MIN-VAL
          TARGET_AREA_X_MIN
          TARGET_AREA_Y_MIN-VAL
          TARGET_AREA_Y_MIN
          TARGET_AREA_X_MAX-VAL
          TARGET_AREA_X_MAX
          TARGET_AREA_Y_MAX-VAL
          TARGET_AREA_Y_MAX
          ATTACK_TARGET_POS-VAL
          ATTACK_TARGET_POS
          FORMATION_POSES-VAL
          FORMATION_POSES
))